SELECT COUNT(*) FROM COOPESOCIOS;

SELECT COUNT(*) FROM MAESTROCLIENTESSALDOS;
SELECT COUNT(*) FROM MOVIMIENTOS;
SELECT COUNT(*) FROM MAESTROPRESTAMOS;
SELECT COUNT(*) FROM PLANPAGOS;
SELECT COUNT(*) FROM CERTIFICADOS;
SELECT COUNT(*) FROM GARANTES;
SELECT COUNT(*) FROM GARANTESDETALLE;
SELECT COUNT(*) FROM GARANTIZADOS;
SELECT COUNT(*) FROM FRA;
SELECT COUNT(*) FROM SINIESTROS;
SELECT COUNT(*) FROM VIDEOS;

SELECT COUNT(*) FROM COOPESOCIOSTEMP;

SELECT COUNT(*) FROM MAESTROCLIENTESSALDOSTEMP;
SELECT COUNT(*) FROM MOVIMIENTOSTEMP;
SELECT COUNT(*) FROM MAESTROPRESTAMOSTEMP;
SELECT COUNT(*) FROM PLANPAGOSTEMP;
SELECT COUNT(*) FROM CERTIFICADOSTEMP;
SELECT COUNT(*) FROM GARANTESTEMP;
SELECT COUNT(*) FROM GARANTESDETALLETEMP;
SELECT COUNT(*) FROM GARANTIZADOSTEMP;
SELECT COUNT(*) FROM FRATEMP;
SELECT COUNT(*) FROM SINIESTROSTEMP;
SELECT COUNT(*) FROM VIDEOSTEMP;

